version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_imgage.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_docker.sh
      timeout: 300
      runas: root
